version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/adage-frontend
    steps:
      - checkout
      - run:
          name: Frontend tests
          command: |
            npm install
            npm test
            npm run build
            if [ ! -f build/static/js/main.js ] || [ ! -f build/static/js/main.js.map ]; then
              echo "main.js or main.js.map not found"
              exit 1
            fi
            if [ ! -f build/static/css/main.css ] || [ ! -f build/static/css/main.css.map ]; then
              echo "main.css or main.css.map not found"
              exit 1
            fi
      - persist_to_workspace:
          root: ~/adage-frontend
          paths:
            - .git
            - build

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/adage-frontend
    steps:
      - attach_workspace:
          at: ~/adage-frontend
      - add_ssh_keys:
          fingerprints:
            - 'a1:30:f0:7e:a3:f4:d1:fc:85:c5:fa:63:b4:93:88:bf'
      - run:
          name: Frontend deployment
          command: |
            ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "rm -rf /tmp/build"
            scp -o StrictHostKeyChecking=no -r ~/adage-frontend/build ${SSH_USER}@${SSH_HOST}:/tmp/
            ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "bash ~/adage-frontend/.circleci/deploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
